# Generated by Django 5.1.2 on 2024-10-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Логин пользователя', max_length=50, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(blank=True, help_text='Имя пользователя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Фамилия пользователя', max_length=50, verbose_name='Фамилия')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('identify', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['login', 'identify', 'registration_date'],
            },
        ),
    ]
