# Generated by Django 5.1.2 on 2024-10-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(blank=True, help_text='Логин пользователя', max_length=50, unique=True, verbose_name='Логин'),
        ),
    ]
