# Generated by Django 5.1.2 on 2024-10-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, help_text='Логин пользователя', max_length=50, verbose_name='Логин'),
        ),
    ]
