# Generated by Django 5.1.2 on 2024-10-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, upload_to='', verbose_name='Фотография пользователя', width_field=100),
        ),
    ]
