# Generated by Django 5.1.2 on 2024-10-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field=100, upload_to='images/', verbose_name='Фотография пользователя', width_field=100),
        ),
    ]
