# Generated by Django 5.1.2 on 2024-10-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identify',
        ),
    ]
